name: Check dbt model naming conventions

on:
  workflow_call:

jobs:
  naming-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Validate model naming conventions (.sql + .yml/.yaml)
        shell: bash
        run: |
          set -euo pipefail
          echo "Checking dbt model naming conventions..."

          # Helper to safely run find only if the directory exists
          find_safe () {
            local dir="$1"; shift
            if [ -d "$dir" ]; then
              # shellcheck disable=SC2068
              find "$dir" -type f \( -name "*.sql" -o -name "*.yml" -o -name "*.yaml" \) $@
            fi
          }

          invalid_staging=""

          # Staging: must start with stg_ except sources
          # Flag any *.sql/*.yml/*.yaml in models/staging that DO NOT start with stg_
          staging_dir="models/staging"
          if [ -d "$staging_dir" ]; then
            invalid_staging=$(find_safe "$staging_dir" \
              -not -name "stg_*.sql" \
              -not -name "stg_*.yml" \
              -not -name "stg_*.yaml" \
              -not -name "*sources*.yml" \
              -not -name "*sources*.yaml" \  
            || true)
          fi

          if [ -n "${invalid_staging:-}" ] ; then
            echo "❌ Invalid model file names detected:"
            if [ -n "${invalid_staging:-}" ]; then
              echo ""
              echo "Models in $staging_dir must start with stg_ (covers .sql, .yml, .yaml):"
              echo "$invalid_staging"
            fi
         
            exit 1
          else
            echo "✅ All model and YAML filenames follow conventions."
          fi