name: Lint SQL with SQLFluff

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  sqlfluff-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('.sqlfluff') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install SQLFluff + dbt-duckdb
        run: |
          python -m pip install --upgrade pip
          # Pin dbt core and adapter to 1.10.10
          pip install "dbt-core==1.10.10" "dbt-duckdb==1.10.10"
          # Install SQLFluff + dbt templater
          pip install "sqlfluff>=3.0.0" "sqlfluff-templater-dbt>=3.0.0"
          sqlfluff version
          dbt --version

      - name: Run SQLFluff lint
        run: |
          set -e
          # Typical dbt project dirs — adjust as needed
          sqlfluff lint models macros seeds snapshots
