# .github/workflows/main-state.yml
name: main-state-build

on:
  push:
    branches: [ main ]
    paths:
      - models/**
      - macros/**
      - seeds/**
      - snapshots/**
      - analyses/**
      - tests/**
      - packages.yml
      - dbt_project.yml
  workflow_dispatch: {}   # lets you run it manually from the Actions tab

jobs:
  build-and-publish-state:
    runs-on: ubuntu-latest
    env:
      DBT_PROFILES_DIR: "."

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dbt + deps
        run: |
          python -m pip install --upgrade pip
          pip install "urllib3<2.0"
          pip install "dbt-core==1.10.10" dbt-duckdb duckdb

      - name: dbt deps
        run: dbt deps

      - name: Full build on main
        run: dbt build

      - name: Upload state artifact (global)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dbt-state-artifacts            # <<< exact name your PR job downloads
          path: target/                        # contains manifest.json, catalog.json, etc.
          retention-days: 30
